Lint/UnusedMethodArgument:
    AllowUnusedKeywordArguments: true

Metrics/LineLength:
    Max: 150
Metrics/ClassLength:
    Max: 500
Metrics/MethodLength:
    Max: 100
Metrics/AbcSize:
    Max: 50

Performance/Casecmp:
    Enabled: false

Style/PreferredHashMethods:
    EnforcedStyle: verbose
Style/MultilineMethodCallIndentation:
    EnforcedStyle: indented
Style/Documentation:
    Enabled: false
Style/FrozenStringLiteralComment:
    Enabled: false
Style/ClassAndModuleChildren:
    Enabled: false
Style/BracesAroundHashParameters:
    Enabled: false
Style/WordArray:
    Enabled: false
